[build]
  functions = "functions"
  command = "npm install pug"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

    
[[headers]]
    for = "/*"
        [headers.values]
            Access-Control-Allow-Origin = "*"